const cache=new Map();
function formatterFor(timeZone){if(!cache.has(timeZone))cache.set(timeZone,new Intl.DateTimeFormat("en-CA",{timeZone,year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit",second:"2-digit",hourCycle:"h23"}));return cache.get(timeZone)}
export function isValidTimeZone(timeZone){try{new Intl.DateTimeFormat("en",{timeZone}).format();return true}catch{return false}}
export function getZonedParts(date,timeZone){if(!isValidTimeZone(timeZone))throw new RangeError(`Unknown time zone: ${timeZone}`);return Object.fromEntries(formatterFor(timeZone).formatToParts(date).filter(({type})=>type!=="literal").map(({type,value})=>[type,Number(value)]))}
function offsetAt(date,timeZone){const p=getZonedParts(date,timeZone);return Date.UTC(p.year,p.month-1,p.day,p.hour,p.minute,p.second)-date.getTime()}
function matches(parts,expected){return["year","month","day","hour","minute"].every(key=>parts[key]===expected[key])}
export function zonedDateTimeToUtc({date,time,timeZone}){if(!/^\d{4}-\d{2}-\d{2}$/.test(date)||!/^\d{2}:\d{2}$/.test(time))throw new TypeError("Use YYYY-MM-DD and HH:MM values.");if(!isValidTimeZone(timeZone))throw new RangeError(`Unknown time zone: ${timeZone}`);const[year,month,day]=date.split("-").map(Number),[hour,minute]=time.split(":").map(Number),expected={year,month,day,hour,minute},wallClock=Date.UTC(year,month-1,day,hour,minute);let instant=wallClock;for(let pass=0;pass<4;pass+=1)instant=wallClock-offsetAt(new Date(instant),timeZone);const result=new Date(instant);if(!matches(getZonedParts(result,timeZone),expected))throw new RangeError("That local time does not exist in the selected zone, usually because of a daylight-saving change.");return result}
export function formatInZone(date,timeZone){if(!isValidTimeZone(timeZone))throw new RangeError(`Unknown time zone: ${timeZone}`);return new Intl.DateTimeFormat("en",{timeZone,weekday:"short",year:"numeric",month:"short",day:"numeric",hour:"numeric",minute:"2-digit",timeZoneName:"short"}).format(date)}
export function workBand(hour){if(hour>=9&&hour<17)return"core";if((hour>=7&&hour<9)||(hour>=17&&hour<20))return"edge";return"off"}
export function buildDayPairs(date,sourceZone,targetZone){if(!isValidTimeZone(sourceZone)||!isValidTimeZone(targetZone))throw new RangeError("Choose valid IANA time zones.");const pairs=[];for(let hour=0;hour<24;hour+=1)try{const instant=zonedDateTimeToUtc({date,time:`${String(hour).padStart(2,"0")}:00`,timeZone:sourceZone}),target=getZonedParts(instant,targetZone);pairs.push({instant,sourceHour:hour,targetHour:target.hour,targetDate:`${target.year}-${String(target.month).padStart(2,"0")}-${String(target.day).padStart(2,"0")}`,sourceBand:workBand(hour),targetBand:workBand(target.hour)})}catch{}return pairs}
